---
params:
  data: NA
  likert: NA
  cat: NA
  num: NA
  NAlab: NA
  scale1: NA
  scale2: NA
  scale3: NA
  scale4: NA
  scale5: NA
  scale6: NA
  scale7: NA
  scale8: NA
  scale9: NA
  scale10: NA
  scale11: NA
  scale12: NA
  scale13: NA
  scale14: NA
  scale15: NA
  scale16: NA
  scale17: NA
  scale18: NA
  scale19: NA
  scale20: NA
output:
  pdf_document:
    toc: yes
  html_document:
    df_print: paged
  word_document:
    reference_docx: style.docx
---
```{r, include = FALSE}
# which are the ordered factors?
# ordvar <- c("Year", "v1", "v3", "v4", "v6", "v7", "v8", "v10")
# which are the unordered factors?
# catvar <- c("ID")
# which are numeric?
#numvar <- c("v2", "v5", "v9")
# which are scales?
# TBD

ordvar <- c("Cond", "MotCheck1", "MotCheck2", "MotCheck3","MsgType1","MsgType2","ValCheck1" ,"ValCheck2","ValCheck3", "age","attbase1.1","attbase1.2","attbase1.3","attbase1.4", "attbase1.5","attbase1.6","attbase1.7","attbase2.1","attbase2.2", "attbase2.3","attbase2.4", "attbase2.5","attbase2.6","attbase2.7","attbase2.8")
numvar <- c("tCogLoadCheck", "tCogLoadList","tInitialEss","tInst","tInst2","tInst3","tInstCogLoad","tMatchedMessage")
catvar <- c()
```

```{r, include = FALSE}
# load these packages
library(psych)
library(tidyverse)
library(knitr)

# chunk options defaults
knitr::opts_chunk$set(dpi = 150, out.width = "50%", out.height = "50%")

source("report_functions.R")

mydata <- read.csv(params$data)
# change responses equal to NAlab to become NAs
mydata[mydata == params$NAlab] <- NA
```

# Continuous Variables

```{r, results= 'asis', warning = FALSE, echo = FALSE, fig.height = 6, fig.width = 8}
for (i in params$num){
  cat("##", i, "\n")
  cat("\n")
  descrip <- destable.cts(i, mydata)
  cat("\n")
  dens(i, data = mydata)
  boxp(i, data = mydata)
  cat("\n")
  print(descrip[["table"]])
  cat('\n')
}
```

\newpage

# Likert Scales

```{r, results= 'asis', warning = FALSE, echo = FALSE, fig.align = "center", fig.height = 8, fig.width = 8}
for (i in params$likert){
  cat("##", i, "\n")
  descrip <- destable.cts(i, data = mydata)
  cat("\n")
  histo(i, data = mydata)
  cat("\n")
  print(freqtab(i, data = mydata))
  print(descrip[["table"]])
  cat("\n")
  cat("\\pagebreak")
}
```

\newpage

# Categorical/Nominal Variables

```{r, results = 'asis', warning = FALSE, echo = FALSE, fig.align = "center", fig.height = 8, fig.width = 8}
for (i in params$cat){
  cat("##", i, "\n")
  cat("\n")
  print(freqtab(i, mydata))
  cat("\n")
}
```

\newpage

# Scales

```{r, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
for(r in 1:20)
{
  # make the variable name to refer to the scale
  scale.name <- paste0("scale", r)
  # save the character vector containing the names of the items that make up the scale
  components <- params[[scale.name]]
  # make a string that concatenates the names of the components
  comp.name <- paste0(components, collapse = ", ")
  # if no scale was specified, return nothing
  if(length(components) == 0)
  {
    return(cat("***"))
  }
  # retrieve the specified columns from the dataframe
  to.scale <- mydata[,components]
  to.scale <- apply(to.scale, 2, FUN = as.numeric)
  # create mean scores
  scale.means <- data.frame(scores = rowMeans(to.scale))
  # change name to relect the items
  names(scale.means) <- comp.name
  # get summary statistics
  descrp <- destable.cts(comp.name, data = scale.means)
  # get reliability statistics
  myscale.info <- scale.info(to.scale)
  
  # outputs
  cat("##", comp.name, "\n")
  cat("\n")
  dens(comp.name, data = scale.means)
  boxp(comp.name, data = scale.means)
  cat("\n")
  print(descrp[["table"]])
  
  cat("**CRONBACH ALPHA** = ", round(myscale.info[["cronalpha"]],3))
  cat("\n\n")
  # print results out in kable tables
  print(kable(myscale.info[["df"]]))
}
```

# Preliminary Diagnostics

## Skewed Variables

```{r, echo = FALSE, results = "asis"}
temp <- data.frame("Skewed" = skews)
if(nrow(temp) == 0)
{
  cat("No Variables With ABS(SKEW) > 1 Detected.")
} else {
  print(kable(temp))
}
```



